# Generated by Django 5.0.6 on 2026-02-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmergencyRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_text", models.TextField(verbose_name="Описание проблемы")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("dtr", "ДТП"),
                            ("criminal", "Уголовное дело"),
                            ("work", "Трудовое право"),
                            ("family", "Семейное право"),
                            ("housing", "Жилищное право"),
                            ("civil", "Гражданское право"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("processing", "В обработке"),
                            ("ai_analyzed", "Проанализирован ИИ"),
                            ("lawyer_assigned", "Назначен юрист"),
                            ("closed", "Закрыт"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "user_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "session_key",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Ключ сессии"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "ai_processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Обработано ИИ"
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос помощи",
                "verbose_name_plural": "Запросы помощи",
                "ordering": ["-created_at"],
            },
        ),
    ]
