# Generated by Django 5.0.6 on 2026-02-04 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexy", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emergencyrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Юридический запрос",
                "verbose_name_plural": "Юридические запросы",
            },
        ),
        migrations.RemoveField(
            model_name="emergencyrequest",
            name="ai_processed_at",
        ),
        migrations.RemoveField(
            model_name="emergencyrequest",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="emergencyrequest",
            name="user_email",
        ),
        migrations.RemoveField(
            model_name="emergencyrequest",
            name="user_phone",
        ),
        migrations.AddField(
            model_name="emergencyrequest",
            name="ai_response",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Ответ ИИ-ассистента"
            ),
        ),
        migrations.AddField(
            model_name="emergencyrequest",
            name="analyzed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата анализа"
            ),
        ),
        migrations.AddField(
            model_name="emergencyrequest",
            name="confidence",
            field=models.FloatField(default=0.0, verbose_name="Уверенность анализа"),
        ),
        migrations.AddField(
            model_name="emergencyrequest",
            name="error_message",
            field=models.TextField(blank=True, verbose_name="Сообщение об ошибке"),
        ),
        migrations.AddField(
            model_name="emergencyrequest",
            name="response_format",
            field=models.CharField(
                choices=[("json", "JSON"), ("text", "Текст")],
                default="json",
                max_length=10,
                verbose_name="Формат ответа",
            ),
        ),
        migrations.AddField(
            model_name="emergencyrequest",
            name="summary",
            field=models.TextField(blank=True, verbose_name="Краткое резюме"),
        ),
        migrations.AddField(
            model_name="emergencyrequest",
            name="urgency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("low", "Низкая"),
                    ("medium", "Средняя"),
                    ("high", "Высокая"),
                    ("critical", "Критическая"),
                ],
                max_length=20,
                verbose_name="Срочность",
            ),
        ),
        migrations.AlterField(
            model_name="emergencyrequest",
            name="category",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Категория дела"
            ),
        ),
        migrations.AlterField(
            model_name="emergencyrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="emergencyrequest",
            name="problem_text",
            field=models.TextField(
                validators=[django.core.validators.MinLengthValidator(20)],
                verbose_name="Описание проблемы",
            ),
        ),
        migrations.AlterField(
            model_name="emergencyrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает анализа"),
                    ("analyzing", "Анализируется ИИ"),
                    ("completed", "Анализ завершен"),
                    ("failed", "Ошибка анализа"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
