# Generated by Django 5.0.6 on 2026-02-04 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexy", "0002_alter_emergencyrequest_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lawyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Имя юриста")),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("auto", "ДТП и автострахование"),
                            ("labor", "Трудовое право"),
                            ("family", "Семейное право"),
                            ("housing", "Жилищное право"),
                            ("criminal", "Уголовное право"),
                            ("civil", "Гражданское право"),
                            ("bankruptcy", "Банкротство"),
                            ("tax", "Налоговое право"),
                            ("immigration", "Миграционное право"),
                            ("intellectual", "Интеллектуальная собственность"),
                            ("consumer", "Защита прав потребителей"),
                            ("military", "Военное право"),
                            ("arbitration", "Арбитражные споры"),
                        ],
                        max_length=50,
                        verbose_name="Специализация",
                    ),
                ),
                (
                    "experience",
                    models.IntegerField(default=0, verbose_name="Опыт работы (лет)"),
                ),
                (
                    "rating",
                    models.FloatField(
                        default=5.0, help_text="От 1 до 5", verbose_name="Рейтинг"
                    ),
                ),
                (
                    "cases_completed",
                    models.IntegerField(default=0, verbose_name="Завершенных дел"),
                ),
                (
                    "success_rate",
                    models.FloatField(
                        default=0.0,
                        help_text="В процентах (0-100)",
                        verbose_name="Процент успешных дел",
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Стоимость услуг"
                    ),
                ),
                (
                    "response_time",
                    models.CharField(
                        default="1-2 часа", max_length=50, verbose_name="Время ответа"
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        default="Пн-Пт, 9:00-18:00",
                        max_length=100,
                        verbose_name="График работы",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Биография")),
                ("education", models.TextField(blank=True, verbose_name="Образование")),
                (
                    "certifications",
                    models.TextField(blank=True, verbose_name="Сертификаты и лицензии"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="lawyers/photos/",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "assistant_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="ID ассистента в Yandex Cloud",
                    ),
                ),
                (
                    "model_uri",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Model URI"
                    ),
                ),
                (
                    "system_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Имя в системе (из инструкций)",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, verbose_name="Доступен для консультаций"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=True, verbose_name="Проверенный юрист"),
                ),
                (
                    "is_premium",
                    models.BooleanField(default=False, verbose_name="Премиум юрист"),
                ),
                (
                    "personality",
                    models.TextField(
                        blank=True, help_text="Описание характера и стиля общения"
                    ),
                ),
                (
                    "demo_messages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Примерные сообщения для демо",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Метки для поиска"
                    ),
                ),
                (
                    "average_response_time_minutes",
                    models.IntegerField(
                        default=60, verbose_name="Среднее время ответа (минут)"
                    ),
                ),
                (
                    "client_satisfaction",
                    models.FloatField(
                        default=0.0, verbose_name="Удовлетворенность клиентов"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Юрист",
                "verbose_name_plural": "Юристы",
                "ordering": ["-rating", "-experience"],
            },
        ),
        migrations.CreateModel(
            name="LawyerChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активный"),
                            ("completed", "Завершен"),
                            ("archived", "В архиве"),
                            ("pending", "Ожидает ответа"),
                            ("closed", "Закрыт"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус чата",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Автоматически генерируется из запроса",
                        max_length=200,
                        verbose_name="Название чата",
                    ),
                ),
                (
                    "message_count",
                    models.IntegerField(default=0, verbose_name="Количество сообщений"),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время последнего сообщения"
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=True, verbose_name="Анонимный чат"),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Имя клиента"
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email клиента"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="lexy.lawyer",
                        verbose_name="Юрист",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="lexy.emergencyrequest",
                        verbose_name="Исходный запрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Чат с юристом",
                "verbose_name_plural": "Чаты с юристами",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consultation_type",
                    models.CharField(
                        choices=[
                            ("chat", "Чат-консультация"),
                            ("call", "Телефонная консультация"),
                            ("video", "Видео-консультация"),
                            ("meeting", "Личная встреча"),
                            ("document", "Подготовка документов"),
                        ],
                        default="chat",
                        max_length=20,
                        verbose_name="Тип консультации",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Запрошена"),
                            ("confirmed", "Подтверждена"),
                            ("in_progress", "В процессе"),
                            ("completed", "Завершена"),
                            ("cancelled", "Отменена"),
                            ("rescheduled", "Перенесена"),
                        ],
                        default="requested",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Запланировано на"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Начало консультации"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Окончание консультации"
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(default=0, verbose_name="Длительность (минут)"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Стоимость",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="Оплачено"),
                ),
                (
                    "client_rating",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Оценка клиента"
                    ),
                ),
                (
                    "client_feedback",
                    models.TextField(blank=True, verbose_name="Отзыв клиента"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="lexy.lawyer",
                        verbose_name="Юрист",
                    ),
                ),
                (
                    "chat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation",
                        to="lexy.lawyerchat",
                        verbose_name="Чат",
                    ),
                ),
            ],
            options={
                "verbose_name": "Консультация",
                "verbose_name_plural": "Консультации",
                "ordering": ["-scheduled_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[
                            ("client", "Клиент"),
                            ("lawyer", "Юрист"),
                            ("system", "Система"),
                            ("assistant", "AI-ассистент"),
                        ],
                        max_length=20,
                        verbose_name="Отправитель",
                    ),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Текст"),
                            ("document", "Документ"),
                            ("image", "Изображение"),
                            ("audio", "Аудио"),
                            ("video", "Видео"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="Тип сообщения",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Прочитано"),
                ),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="Редактировано"),
                ),
                (
                    "ai_response_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Данные ответа ИИ"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес отправителя"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="lexy.lawyerchat",
                        verbose_name="Чат",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение чата",
                "verbose_name_plural": "Сообщения чатов",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="LawyerReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=100, verbose_name="Имя клиента"),
                ),
                (
                    "client_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email клиента"
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "★☆☆☆☆"),
                            (2, "★★☆☆☆"),
                            (3, "★★★☆☆"),
                            (4, "★★★★☆"),
                            (5, "★★★★★"),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, verbose_name="Проверенный отзыв"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=True, verbose_name="Одобрен к публикации"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="lexy.consultation",
                        verbose_name="Консультация",
                    ),
                ),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="lexy.lawyer",
                        verbose_name="Юрист",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв о юристе",
                "verbose_name_plural": "Отзывы о юристах",
                "ordering": ["-created_at"],
            },
        ),
    ]
