# Generated by Django 5.0.6 on 2026-02-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexy", "0003_lawyer_lawyerchat_consultation_chatmessage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lawyerchat",
            name="lawyer_agent_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ID AI-агента юриста"
            ),
        ),
        migrations.AddField(
            model_name="lawyerchat",
            name="lawyer_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Имя юриста (из агента)"
            ),
        ),
        migrations.AddField(
            model_name="lawyerchat",
            name="lawyer_specialization",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Специализация (из агента)"
            ),
        ),
    ]
